export const ActionType = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',

    RESET_CART: 'RESET_CART',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
}
